   name: Update Credly Badges
   on:
     schedule:
       - cron: "0 2   *"  # Runs daily at 2am UTC
     workflow_dispatch:     # Allows manual trigger
   permissions:
     contents: write
   jobs:
     update-readme:
       name: Update README with Credly badges
       runs-on: ubuntu-latest
       steps:
         - name: Badges - Readme
           uses: pemtajo/badge-readme@main
           with:
             CREDLYUSER: zachary-way
   